package com.manulife.bigdata.scala.chapter09.exception

object Test02_Throw {
  def main(args: Array[String]): Unit = {
    throw new Exception("俺的Error")
  }

}
